In [29]:
import pandas as pd
import sqlite3

In [30]:
conn = sqlite3.connect('./data/mock_logs.db')

pd.read_sql_query(
    "SELECT name, sql FROM sqlite_master WHERE type='table';",
    conn
)

              name                                                sql
0     decision_log  CREATE TABLE decision_log (\n        impressio...
1  interaction_log  CREATE TABLE interaction_log (\n        id INT...
2  sqlite_sequence             CREATE TABLE sqlite_sequence(name,seq)

In [43]:
df_send = pd.read_sql_query("SELECT * FROM decision_log", conn)
df_send

,impression_id,episode_id,step_t,user_id,campaign_id,policy_name,encoder_version,propensity_score,is_explore,decision_reason,context_json,next_context_json,chosen_action_json,candidate_actions_json,served_timestamp,reward_window_end,attributed_reward_version,done_flag,ui_payload
0,f95b31f3-1703-435e-b827-1b65122b7b95,2c121580-9ef5-474f-8d57-56ada3c5e628,1,tmn.10000971872,BUDDY_SCENARIO_87_48b812d5,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""unknown"", ""trigger_scenario""...",None,"{""campaign_id"": ""BUDDY_SCENARIO_87_48b812d5"", ...","[{""campaign_id"": ""4"", ""domain"": ""DCP_ALP"", ""ba...",2026-04-25T19:32:03.198204,2026-04-26T19:32:03.198204,v1.1,0,"{""impression_id"": ""f95b31f3-1703-435e-b827-1b6..."
1,82b126d8-3a22-472c-a5e1-b517007d3809,8f5e8fae-5afe-4b02-a6c4-6ecfca176fe9,1,tmn.10082112804,BUDDY_SCENARIO_105_e6152bd7,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""top_spend"", ""trigger_scenari...",None,"{""campaign_id"": ""BUDDY_SCENARIO_105_e6152bd7"",...","[{""campaign_id"": ""1166"", ""domain"": ""PMS"", ""ban...",2026-04-25T19:32:04.403221,2026-04-26T19:32:04.403221,v1.1,0,"{""impression_id"": ""82b126d8-3a22-472c-a5e1-b51..."
2,398e5cda-55fd-4183-839b-0d1472f8624c,405488a2-ac6f-4813-9e60-32fb8f23b3af,1,tmn.10082112804,BUDDY_SCENARIO_106_54238287,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""unknown"", ""trigger_scenario""...",None,"{""campaign_id"": ""BUDDY_SCENARIO_106_54238287"",...","[{""campaign_id"": ""8"", ""domain"": ""ONL_TIKTOK"", ...",2026-04-25T19:32:05.619987,2026-04-26T19:32:05.619987,v1.1,0,"{""impression_id"": ""398e5cda-55fd-4183-839b-0d1..."
3,2c8068f2-e62a-426c-a97d-f9767f877db5,3563cf35-46e2-4e52-b64b-b062fde04d62,1,tmn.10082112804,BUDDY_SCENARIO_7_584adcde,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""unknown"", ""trigger_scenario""...",None,"{""campaign_id"": ""BUDDY_SCENARIO_7_584adcde"", ""...","[{""campaign_id"": ""7"", ""domain"": ""ONL_GRAB"", ""b...",2026-04-25T19:32:06.933875,2026-04-26T19:32:06.933875,v1.1,0,"{""impression_id"": ""2c8068f2-e62a-426c-a97d-f97..."
4,070d11ff-bf18-4311-a1c8-6a0ec968640d,81053db5-570d-4b0b-a684-772d9a324f17,1,tmn.10082112804,BUDDY_SCENARIO_83_dc037bfb,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""top_spend"", ""trigger_scenari...",None,"{""campaign_id"": ""BUDDY_SCENARIO_83_dc037bfb"", ...","[{""campaign_id"": ""1166"", ""domain"": ""PMS"", ""ban...",2026-04-25T19:32:08.061173,2026-04-26T19:32:08.061173,v1.1,0,"{""impression_id"": ""070d11ff-bf18-4311-a1c8-6a0..."
5,bbb442ed-9105-4964-8313-9d4cab6707e5,58e7fab6-3357-4b56-92d7-87d510e63829,1,tmn.10086632327,3_917bd430,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""unknown"", ""trigger_scenario""...",None,"{""campaign_id"": ""3_917bd430"", ""domain"": ""711"",...","[{""campaign_id"": ""1049"", ""domain"": ""711"", ""ban...",2026-04-25T19:32:09.274020,2026-04-26T19:32:09.274020,v1.1,0,"{""impression_id"": ""bbb442ed-9105-4964-8313-9d4..."
6,7b00d36e-b8e5-44f3-8cd2-aa0770c28ac4,9d96b873-5d5b-4151-8111-b99e8132362b,1,tmn.10086632327,BUDDY_SCENARIO_81_060a52e4,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""top_spend"", ""trigger_scenari...",None,"{""campaign_id"": ""BUDDY_SCENARIO_81_060a52e4"", ...","[{""campaign_id"": ""1058"", ""domain"": ""RET_LTS"", ...",2026-04-25T19:32:10.469079,2026-04-26T19:32:10.469079,v1.1,0,"{""impression_id"": ""7b00d36e-b8e5-44f3-8cd2-aa0..."
7,29cba52e-00cb-4a1c-b1c9-7f82085488a5,20333a0d-d118-4b78-b2df-e3acf8e04e49,1,tmn.10086632327,BUDDY_SCENARIO_83_6ebea952,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""top_spend"", ""trigger_scenari...",None,"{""campaign_id"": ""BUDDY_SCENARIO_83_6ebea952"", ...","[{""campaign_id"": ""1058"", ""domain"": ""RET_LTS"", ...",2026-04-25T19:32:11.705606,2026-04-26T19:32:11.705606,v1.1,1,"{""impression_id"": ""29cba52e-00cb-4a1c-b1c9-7f8..."
8,637c7f68-0148-4b13-a3e1-fd6e32441b5e,98b12055-f75d-42ff-8a19-24e4ab9b019d,1,tmn.10112652121,3_504bb2cc,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""unknown"", ""trigger_scenario""...",None,"{""campaign_id"": ""3_504bb2cc"", ""domain"": ""711"",...","[{""campaign_id"": ""1048"", ""domain"": ""711"", ""ban...",2026-04-25T19:32:12.882510,2026-04-26T19:32:12.882510,v1.1,0,"{""impression_id"": ""637c7f68-0148-4b13-a3e1-fd6..."
9,30e0e32f-5483-4b9a-82af-3b77833cb8bc,633db402-d8c6-43b9-b4a1-3eb33548f2ad,1,tmn.10112652121,BUDDY_SCENARIO_81_a72b3db4,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""top_spend"", ""trigger_scenari...",None,"{""campaign_id"": ""BUDDY_SCENARIO_81_a72b3db4"", ...","[{""campaign_id"": ""108"", ""domain"": ""PMS"", ""band...",2026-04-25T19:32:14.101970,2026-04-26T19:32:14.101970,v1.1,0,"{""impression_id"": ""30e0e32f-5483-4b9a-82af-3b7..."
10,fe7f9451-5672-4ae7-aca7-3e8b61699d74,1759e243-cea0-449e-8ce7-0081a7c80c5a,1,tmn.10112652121,BUDDY_SCENARIO_83_1b561188,Bayesian_Intent_Fusion_v5,RFM_Attention_Encoder_v2,0.9,0,unknown,"{""user_segment"": ""top_spend"", ""trigger_scenari...",None,"{""campaign_id"": ""BUDDY_SCENARIO_83_1b561188"", ...","[{""campaign_id"": ""108"", ""domain"": ""PMS"", ""band...",2026-04-25T19:32:15.330532,2026-04-26T19:32:15.330532,v1.1,0,"{""impression_id"": ""fe7f9451-5672-4ae7-aca7-3e8..."

In [31]:
df_action = pd.read_sql_query("SELECT * FROM interaction_log", conn)
df_action

,id,impression_id,event_type,reward_value,is_terminal_reward,event_timestamp,delay_seconds
0,1,6e8187ab-e646-4d95-b34c-d8b1b7b57783,IMPRESSION,NaN,0,2026-05-24T08:17:49.865588+07:00,0.000000
1,2,39e55d9e-e9d0-4d07-b0c4-d9d6e3052b9b,IMPRESSION,NaN,0,2026-05-24T08:17:50.939202+07:00,0.000000
2,3,39cdf48b-3a27-4473-ae88-e10e7e953852,IMPRESSION,NaN,0,2026-05-24T08:17:52.078801+07:00,0.000000
3,4,89954a2b-8d53-4c60-8f75-66200a59dafd,IMPRESSION,NaN,0,2026-05-24T08:17:53.170689+07:00,0.000000
4,5,232d357a-5a7c-494a-bb07-2fb3e96e20f3,IMPRESSION,NaN,0,2026-05-24T08:17:54.270844+07:00,0.000000
5,6,f06d2c07-3d5d-4d2e-98db-f739d5154d99,IMPRESSION,NaN,0,2026-05-24T08:17:55.389784+07:00,0.000000
6,7,3f1bba7c-a635-4949-a483-f3c96ad1930c,IMPRESSION,NaN,0,2026-05-24T08:17:56.472345+07:00,0.000000
7,8,535c3b63-4c11-4a90-b2dc-180badc12e0c,IMPRESSION,NaN,0,2026-05-24T08:17:57.532515+07:00,0.000000
8,9,c78526c7-619a-4361-91eb-f30d9f19f694,IMPRESSION,NaN,0,2026-05-24T08:17:58.612067+07:00,0.000000
9,10,34e5b3f7-bce8-4794-85e1-7f2c089c4667,IMPRESSION,NaN,0,2026-05-24T08:17:59.690944+07:00,0.000000
10,11,e1ac9906-b5ec-43c1-85f3-35a27c5294c5,IMPRESSION,NaN,0,2026-05-24T08:18:00.772912+07:00,0.000000
11,12,7d61cc9d-e305-43ee-86fc-f639b70b2715,IMPRESSION,NaN,0,2026-05-24T08:18:01.841839+07:00,0.000000
12,13,913d04f1-3605-40e3-82fa-2050da17d470,IMPRESSION,NaN,0,2026-05-24T08:18:02.964904+07:00,0.000000
13,14,d738feb5-85cd-4179-ab7e-5bd35f87b06f,IMPRESSION,NaN,0,2026-05-24T08:18:04.032381+07:00,0.000000
14,15,5224c840-15b3-4e9a-b715-de9524947a77,IMPRESSION,NaN,0,2026-05-24T08:18:05.095996+07:00,0.000000
15,16,2de0359a-0acc-49d2-94f0-4687a1cedd33,IMPRESSION,NaN,0,2026-05-24T08:18:06.180119+07:00,0.000000
16,17,ab4ccd03-8add-453d-912f-05fb0fc0258c,IMPRESSION,NaN,0,2026-05-24T08:18:07.366850+07:00,0.000000
17,18,eae572d1-0f72-4844-9238-0c158bb5999a,IMPRESSION,NaN,0,2026-05-24T08:18:08.498687+07:00,0.000000
18,19,197e0f79-458b-4020-bd83-a263380c3b2f,IMPRESSION,NaN,0,2026-05-24T08:18:09.576306+07:00,0.000000
19,20,45a5ece9-9df2-40ba-8fc3-72686826513e,IMPRESSION,NaN,0,2026-05-24T08:18:10.657275+07:00,0.000000
20,21,efec97f0-8f15-4928-9d1c-a16d09096264,IMPRESSION,NaN,0,2026-05-24T08:18:11.742467+07:00,0.000000
21,22,b8191aab-ef9c-4492-9c97-938ed2dc1935,IMPRESSION,NaN,0,2026-05-24T08:18:12.839048+07:00,0.000000
22,23,ab4ccd03-8add-453d-912f-05fb0fc0258c,OPEN,1.0,1,2026-05-24T08:18:33.364287+07:00,25.997437
23,24,eae572d1-0f72-4844-9238-0c158bb5999a,DISMISS,-0.5,1,2026-05-24T08:18:38.301933+07:00,29.803246
24,25,197e0f79-458b-4020-bd83-a263380c3b2f,DISMISS,-0.5,1,2026-05-24T08:18:41.232395+07:00,31.656089
25,26,45a5ece9-9df2-40ba-8fc3-72686826513e,DISMISS,-0.5,1,2026-05-24T08:18:42.164314+07:00,31.507039
26,27,efec97f0-8f15-4928-9d1c-a16d09096264,OPEN,1.0,1,2026-05-24T08:18:43.648872+07:00,31.906405
27,28,b8191aab-ef9c-4492-9c97-938ed2dc1935,OPEN,1.0,1,2026-05-24T08:18:46.283429+07:00,33.444381
28,29,7d61cc9d-e305-43ee-86fc-f639b70b2715,OPEN,1.0,1,2026-05-24T08:18:58.120610+07:00,56.278771
29,30,d738feb5-85cd-4179-ab7e-5bd35f87b06f,DISMISS,-0.5,1,2026-05-24T08:19:03.736052+07:00,59.703671
30,31,913d04f1-3605-40e3-82fa-2050da17d470,DISMISS,-0.5,1,2026-05-24T08:19:04.848708+07:00,61.883804
31,32,5224c840-15b3-4e9a-b715-de9524947a77,OPEN,1.0,1,2026-05-24T08:19:06.531630+07:00,61.435634
32,33,e1ac9906-b5ec-43c1-85f3-35a27c5294c5,DISMISS,-0.5,1,2026-05-24T08:19:08.863532+07:00,68.090620
33,34,2de0359a-0acc-49d2-94f0-4687a1cedd33,DISMISS,-0.5,1,2026-05-24T08:19:09.514827+07:00,63.334708
34,35,39cdf48b-3a27-4473-ae88-e10e7e953852,DISMISS,-0.5,1,2026-05-24T08:19:11.366584+07:00,79.287783
35,36,89954a2b-8d53-4c60-8f75-66200a59dafd,DISMISS,-0.5,1,2026-05-24T08:19:12.232762+07:00,79.062073
36,37,232d357a-5a7c-494a-bb07-2fb3e96e20f3,OPEN,1.0,1,2026-05-24T08:19:14.415229+07:00,80.144385
37,38,3f1bba7c-a635-4949-a483-f3c96ad1930c,DISMISS,-0.5,1,2026-05-24T08:19:17.385544+07:00,80.913199
38,39,535c3b63-4c11-4a90-b2dc-180badc12e0c,DISMISS,-0.5,1,2026-05-24T08:19:19.031746+07:00,81.499231
39,40,39e55d9e-e9d0-4d07-b0c4-d9d6e3052b9b,OPEN,1.0,1,2026-05-24T08:19:22.016711+07:00,91.077509
40,41,6e8187ab-e646-4d95-b34c-d8b1b7b57783,OPEN,1.0,1,2026-05-24T08:19:25.232910+07:00,95.367322

In [45]:
sqlite_se = pd.read_sql_query("SELECT * FROM sqlite_sequence;", conn)
sqlite_se

              name  seq
0  interaction_log   14

In [48]:
bu_df = pd.read_csv("feedback/feedback_data.csv")
bu_df

,Impression_ID,TMNID,Scenario,Campaign_ID,Domain,Model_Version,Last_Action,Reward_Score,Sent_At
0,a2fdb7b9-40ce-486f-8d91-50f7ca9023ef,tmn.10112652121,NaN,BUDDY_SCENARIO_83_a477c374,PMS,Bayesian_Intent_Fusion_v5,IMPRESSION,0.0,2026-04-27T09:51:35.338325
1,35eb913c-6616-481d-9779-c5512cdadcbe,tmn.10112652121,NaN,BUDDY_SCENARIO_81_15826833,ONL_ODM,Bayesian_Intent_Fusion_v5,IMPRESSION,-0.5,2026-04-27T09:51:34.206036
2,4f30115a-9f16-4092-a789-ab70669125b1,tmn.10112652121,NaN,3_5a5c0735,711,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-27T09:51:33.158391
3,f69bd3fa-dfcc-4083-b40f-33ea8cfc52f4,tmn.10086632327,NaN,BUDDY_SCENARIO_83_25b3529c,PMS,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-27T09:51:32.111030
4,9c6fcad8-bb49-4e58-85c2-480161494faf,tmn.10086632327,NaN,BUDDY_SCENARIO_81_49d86448,PMS,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-27T09:51:31.039353
5,7f6bae4f-ed3c-4618-92e7-c21aa0a1763c,tmn.10086632327,NaN,3_f50b66ae,711,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-27T09:51:29.990100
6,d6a34074-bd43-486b-96e0-bf84b219ccad,tmn.10082112804,NaN,BUDDY_SCENARIO_83_f276930e,PMS,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-27T09:51:28.947368
7,84a7b1ee-c9a8-4594-848a-5d78e803a00a,tmn.10082112804,NaN,BUDDY_SCENARIO_7_810ab199,ONL_GRAB,Bayesian_Intent_Fusion_v5,IMPRESSION,-0.5,2026-04-27T09:51:27.902579
8,9ef1e07c-0200-4392-8182-a5734a182d8e,tmn.10082112804,NaN,BUDDY_SCENARIO_106_caeecee0,ONL_TIKTOK,Bayesian_Intent_Fusion_v5,IMPRESSION,-0.5,2026-04-27T09:51:26.830570
9,eef0cc84-f2b3-419d-8680-ea852328ec66,tmn.10082112804,NaN,BUDDY_SCENARIO_105_93489496,PMS,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-27T09:51:25.784757
10,aac12e43-b1ed-4a63-8039-e5368ace6d3d,tmn.10000971872,NaN,BUDDY_SCENARIO_87_8ebf05d9,DCP_ALP,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-27T09:51:24.756137

In [13]:
pd.read_csv("feedback/feedback_data.csv")

,Impression_ID,TMNID,Scenario,Campaign_ID,Domain,Model_Version,Last_Action,Reward_Score,Sent_At
0,4518078c-140f-44be-9a70-a21c3297f865,tmn.10112652121,NaN,BUDDY_SCENARIO_83_aaf3ae33,PMS,Bayesian_Intent_Fusion_v5,IMPRESSION,0.0,2026-04-28T09:14:06.434977
1,b1ac53b5-f184-4abb-a0a9-7c395f2fad61,tmn.10112652121,NaN,BUDDY_SCENARIO_81_39dea7e7,PMS,Bayesian_Intent_Fusion_v5,IMPRESSION,0.0,2026-04-28T09:14:05.369621
2,47ccbf92-27cd-4bac-b265-ce46ff8d180b,tmn.10112652121,NaN,3_b83e7923,711,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-28T09:14:04.299616
3,8aea4545-0665-4c39-9bb4-6230fc8a8be4,tmn.10086632327,NaN,BUDDY_SCENARIO_83_7ba8dcc2,RET_KA,Bayesian_Intent_Fusion_v5,IMPRESSION,0.0,2026-04-28T09:14:03.243754
4,80a15ae2-3a8e-4295-b013-4c6d770008f0,tmn.10086632327,NaN,BUDDY_SCENARIO_81_56db10c8,RET_KA,Bayesian_Intent_Fusion_v5,IMPRESSION,-0.5,2026-04-28T09:14:02.213278
5,f01c01e5-317a-456f-b99b-59459babe933,tmn.10086632327,NaN,3_23d7f90a,711,Bayesian_Intent_Fusion_v5,IMPRESSION,0.0,2026-04-28T09:14:01.148346
6,02534aa3-520f-4b8a-ace7-df98c55f5d7a,tmn.10082112804,NaN,BUDDY_SCENARIO_83_e5b7677e,PMS,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-28T09:14:00.069823
7,6e0f7a69-be8a-4aa5-be29-514711075213,tmn.10082112804,NaN,BUDDY_SCENARIO_7_ddd2bb24,ONL_GRAB,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-28T09:13:59.014045
8,db644a3f-dbc0-456a-beca-95abe2910e3c,tmn.10082112804,NaN,BUDDY_SCENARIO_106_0cd6904f,PMS,Bayesian_Intent_Fusion_v5,IMPRESSION,-0.5,2026-04-28T09:13:57.952718
9,ececd6d5-538c-4707-b42a-c3449b8066b2,tmn.10082112804,NaN,BUDDY_SCENARIO_105_44cf7eaf,PMS,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-28T09:13:56.898907
10,712d9b14-d301-40b0-9f4a-a48a6a18f722,tmn.10000971872,NaN,BUDDY_SCENARIO_87_8bdcf355,DCP_ALP,Bayesian_Intent_Fusion_v5,OPEN,1.0,2026-04-28T09:13:55.843400

In [14]:
import pandas as pd

data = pd.read_csv("feedback/feedback_posterior.csv")
data

,Impression_ID,TMNID,Campaign_ID,Domain,arm_campaign,Last_Action,Reward_Score,Sent_At
0,2a0df755-659f-4416-9ffe-95de39fb3a0b,tmn.10086632327,TEST_CAMP_001,PMS,83.0,DISMISS,-0.5,2026-05-19T03:07:24.626748
1,eb50712c-7d0b-43c3-96e3-036f00bcc6d4,tmn.10086632327,TEST_CAMP_001,PMS,83.0,DISMISS,-0.5,2026-05-15T07:40:05.161351
2,61baa925-1371-4462-904c-909e44ec32f5,tmn.10086632327,TEST_CAMP_001,PMS,83.0,OPEN,1.0,2026-05-15T07:28:57.555244
3,d9fb2eaf-299e-42a7-9476-97d8678e31b5,tmn.10112652121,BUDDY_SCENARIO_83_da540183,PMS,NaN,DISMISS,-0.5,2026-05-13T10:30:02.658413
4,4dcc6c8b-7d7c-47d0-8796-f957cb2ba66b,tmn.10112652121,BUDDY_SCENARIO_81_73f4ecee,PMS,NaN,OPEN,1.0,2026-05-13T10:30:01.582406
5,474a9927-9a18-4225-bf53-ff96dec4d21a,tmn.10112652121,3_efce05d2,711,NaN,OPEN,1.0,2026-05-13T10:30:00.499203
6,1f3f62fa-3980-46dd-a9e0-202aa62737ed,tmn.10086632327,BUDDY_SCENARIO_83_d1b77c53,PMS,NaN,OPEN,1.0,2026-05-13T10:29:59.393033
7,8c0a6189-2d85-4717-9772-c7ed4cf540dd,tmn.10086632327,BUDDY_SCENARIO_81_6d3246b6,PMS,NaN,OPEN,1.0,2026-05-13T10:29:58.338351
8,83a1a1c7-c9d7-4ea9-aac0-cb592cd43c1a,tmn.10086632327,3_0a08ce59,711,NaN,OPEN,1.0,2026-05-13T10:29:57.258218
9,6ef70c54-1d90-40a9-8af6-9ba048e6b379,tmn.10082112804,BUDDY_SCENARIO_106_1100340c,ONL_TIKTOK,NaN,OPEN,1.0,2026-05-13T10:29:56.183247
10,11ba402c-e83b-44b6-801e-7f8349263483,tmn.10082112804,BUDDY_SCENARIO_105_e76fb97a,PMS,NaN,OPEN,1.0,2026-05-13T10:29:55.145400
11,c0c37b52-544c-4e7f-b881-0ef0177ac7b3,tmn.10082112804,BUDDY_SCENARIO_83_9d6c4593,PMS,NaN,OPEN,1.0,2026-05-13T10:29:54.092829
12,22e551d5-7816-4122-80b4-aa308b57d61b,tmn.10082112804,BUDDY_SCENARIO_7_9941f647,ONL_GRAB,NaN,OPEN,1.0,2026-05-13T10:29:53.047394
13,a2a9e067-8484-4bc7-a730-3c66db0711ed,tmn.10000971872,BUDDY_SCENARIO_87_97054527,DCP_ALP,NaN,OPEN,1.0,2026-05-13T10:29:52.006636

In [18]:
abc = pd.read_csv("feedback/feedback_llm_state.csv")
abc

,TMNID,Campaign_ID,Domain,arm_campaign,Sent_Title,Sent_Msg,Last_Action,Reward_Score,Sent_At
0,tmn.10112652121,BUDDY_SCENARIO_1167_f6aad74d,PMS,NaN,สรุปยอด SoF เดือนนี้ ช้อปปังแค่ไหน!,Non! เดือนมีนาคม 2026 ใช้ SoF ไป 178 บาท! มาเช...,IMPRESSION,0.0,2026-05-21T14:11:37.768198+07:00
1,tmn.10112652121,BUDDY_SCENARIO_1166_ef1facb6,PMS,NaN,สรุปยอด E-Wallet ของ Non มาแล้วจ้า,Non รู้ยัง? เดือนนี้ใช้ E-Wallet SoF ไป 178 บา...,IMPRESSION,0.0,2026-05-21T14:11:36.688076+07:00
2,tmn.10112652121,BUDDY_SCENARIO_108_dc6a4e63,PMS,NaN,เงินเก็บปังๆ เริ่มได้เลย,เห็นยอดใช้จ่ายแล้วป่ะ? มาลองตั้งเป้าเก็บเงินกั...,OPEN,1.0,2026-05-21T14:11:35.560987+07:00
3,tmn.10112652121,3_78b46f05,711,NaN,เซเว่นยืนหนึ่ง! ช้อปฟิน บันทึกปังๆ,ยอด 7-11 พุ่งปรี๊ด! จ่ายผ่านแอปคือดีย์ แถมบันท...,OPEN,1.0,2026-05-21T14:11:34.487207+07:00
4,tmn.10112652121,3_1be807a8,711,NaN,ขาช้อป 7-Eleven ตัวจริง!,7-Eleven ยืนหนึ่ง! สัปดาห์นี้มาจัดเต็มอีกรอบกั...,DISMISS,-0.5,2026-05-21T14:11:33.410235+07:00
5,tmn.10112652121,3_aeeaddc0,711,NaN,ติดเซเว่นเบอร์นี้ได้ไง!,ยอดใช้จ่ายเซเว่น Non ปังไม่ไหว! สแกน All Membe...,DISMISS,-0.5,2026-05-21T14:11:32.319387+07:00
6,tmn.10086632327,BUDDY_SCENARIO_1167_70f22e68,PMS,NaN,สรุป E-Wallet เดือนนี้ ว้าวมากแม่!,เดือน มี.ค. นี้ แจ็คใช้จ่ายผ่าน E-Wallet SoF ไ...,IMPRESSION,0.0,2026-05-21T14:11:31.259356+07:00
7,tmn.10086632327,BUDDY_SCENARIO_1166_118967af,PMS,NaN,สรุปยอดใช้ E-Wallet เดือนนี้รู้ยัง?,ยอดใช้ E-Wallet SoF เดือนมีนาคม 1614 บาท! มาเช...,DISMISS,-0.5,2026-05-21T14:11:30.130016+07:00
8,tmn.10086632327,BUDDY_SCENARIO_108_1c6ed2fd,PMS,NaN,เก็บเงินให้ปัง ทำได้ชิลล์ๆ!,Jack ใช้ E-Wallet คล่องปร๋อ! มาลองปั้นเงินเก็บ...,DISMISS,-0.5,2026-05-21T14:11:29.049956+07:00
9,tmn.10086632327,3_69f700b4,711,NaN,ขาประจำเซเว่นมาทางนี้!,ขาประจำเซเว่นมาทางนี้! ช้อปของอร่อยเติมพลังง่า...,OPEN,1.0,2026-05-21T14:11:27.981728+07:00
10,tmn.10086632327,3_e9fb2dd2,711,NaN,7-11 แวะบ่อยขนาดนี้เลย,Jack สัปดาห์นี้ 7-11 คือที่สุด! แวะบ่อยขนาดนี้...,OPEN,1.0,2026-05-21T14:11:26.822523+07:00
11,tmn.10086632327,3_585742b2,711,NaN,7-ELEVEN ที่สุดของแจ็ค!,แจ็คปักหลัก 7-ELEVEN ตลอด! เข้าบ่อยเบอร์นี้ อย...,DISMISS,-0.5,2026-05-21T14:11:25.729879+07:00
12,tmn.10082112804,BUDDY_SCENARIO_1097_6a7b53bc,ONL_TIKTOK,NaN,TikTok ช้อปเก่งงง! สรุปให้ดู,อยากรู้ป่ะ TikTok ช้อปอะไรไปบ้าง? มาดูสรุปให้เ...,IMPRESSION,0.0,2026-05-21T14:11:24.605428+07:00
13,tmn.10082112804,BUDDY_SCENARIO_1102_b2f4a61c,ONL_TIKTOK,NaN,TikTok ช้อปเพลิน สรุปยอดด่วน!,Double Day นี้ต้องจัดเต็ม! มาเช็กยอด TikTok ที...,DISMISS,-0.5,2026-05-21T14:11:23.515705+07:00
14,tmn.10082112804,BUDDY_SCENARIO_1100_47fe1fe0,ONL_TIKTOK,NaN,ช้อป TikTok ดับเบิลเดย์นี้ต้องปัง!,ดับเบิลเดย์มาแล้ว ช้อป TikTok อย่าเพิ่งรีบเอฟ!...,DISMISS,-0.5,2026-05-21T14:11:22.425167+07:00
15,tmn.10082112804,BUDDY_SCENARIO_1167_7b8122d6,PMS,NaN,อุ๊ย! งบหมวดนี้ใกล้จะเต็มแล้วนะ,เดือนนี้ดูเหมือนจะใช้เงินหมวดช้อปปิ้งเพลินไปนิ...,IMPRESSION,0.0,2026-05-21T14:11:21.328364+07:00
16,tmn.10082112804,BUDDY_SCENARIO_1166_70db0422,PMS,NaN,กินข้าวแล้ว จ่ายเท่าไหร่กันนะ?,Guy เข้ามาบ่อยขนาดนี้ ลองจดรายจ่ายดูยัง? แค่แป...,OPEN,1.0,2026-05-21T14:11:20.189149+07:00
17,tmn.10082112804,BUDDY_SCENARIO_108_62c2eda8,PMS,NaN,เข้าแอปบ่อย ลองเก็บเงินปังๆ ยัง?,เข้าแอปบ่อยๆ ลองมาเปิดประสบการณ์ใหม่กับ MoneyB...,DISMISS,-0.5,2026-05-21T14:11:19.121428+07:00
18,tmn.10082112804,BUDDY_SCENARIO_1095_2e745231,ONL_GRAB,NaN,Grab นี่แหละ ตัวท็อปเปย์ตัวจริง?,ส่องสถิติเปย์ Grab ด่วน! จะได้รู้ว่าทุ่มไปเท่า...,DISMISS,-0.5,2026-05-21T14:11:18.038170+07:00
19,tmn.10082112804,BUDDY_SCENARIO_1090_4688f804,ONL_GRAB,NaN,ชาว Grab ต้องรู้! ฟินแล้วอย่าลืม,ฟินมื้อนี้แล้ว แวะมาบันทึกยอดหน่อย Money Buddy...,OPEN,1.0,2026-05-21T14:11:16.966571+07:00
20,tmn.10082112804,BUDDY_SCENARIO_121_0fc7b80d,ONL_GRAB,NaN,หิวปะ? Grab เลยดิเพื่อน!,ได้เวลาฟิน! สั่ง Grab ผ่าน MoneyBuddy ตอนนี้ ร...,OPEN,1.0,2026-05-21T14:11:15.898854+07:00
21,tmn.10000971872,BUDDY_SCENARIO_1079_9754b46b,DCP_ALP,NaN,แอปโปรดคุณรออยู่!,พี่จิงคะ พักเรื่องงาน มาสนุกกับแอปและเกมโปรดที...,OPEN,1.0,2026-05-21T14:11:14.827421+07:00
22,tmn.10000971872,BUDDY_SCENARIO_4_87063c8e,DCP_ALP,NaN,เช็กยอดใช้จ่ายบริการดิจิทัล,P'Jing ลองมาเช็กยอดใช้จ่ายกับบริการดิจิทัลกัน!...,OPEN,1.0,2026-05-21T14:11:13.750002+07:00
23,tmn.10000971872,BUDDY_SCENARIO_1071_a51cbddc,DCP_ALP,NaN,อยากได้อะไร ให้เราช่วยเก็บนะ P'Jing,P'Jing เหนื่อยแล้วใช่ไหม? มาวางแผนเก็บเงินเพื่...,DISMISS,-0.5,2026-05-21T14:11:12.660524+07:00

In [21]:
main_data = pd.read_csv("feedback/feedback_data.csv")
main_data.columns

Index(['Impression_ID', 'TMNID', 'Scenario', 'Campaign_ID', 'Domain',
       'Model_Version', 'Last_Action', 'Reward_Score', 'Sent_At'],
      dtype='str')

In [27]:
poster = pd.read_csv("feedback/feedback_posterior.csv")
poster.columns

Index(['Impression_ID', 'TMNID', 'Campaign_ID', 'Domain', 'arm_campaign',
       'Last_Action', 'Reward_Score', 'Sent_At'],
      dtype='str')

In [25]:
llm = pd.read_csv("feedback/feedback_llm_state.csv")
llm.columns

Index(['TMNID', 'Campaign_ID', 'Domain', 'arm_campaign', 'Sent_Title',
       'Sent_Msg', 'Last_Action', 'Reward_Score', 'Sent_At'],
      dtype='str')